#include "TeWidgetToolBar.h"

#include "../TeEditor.h"
#include "Math/TeMath.h"
#include "TeWidgetRenderOptions.h"
#include "Animation/TeAnimationManager.h"
#include "Scripting/TeScriptManager.h"
#include "Manager/TeRenderDocManager.h"
#include "Scene/TeSceneManager.h"
#include "ImGuizmo/ImGuizmo.h"
#include "Renderer/TeRenderer.h"
#include "Components/TeCLight.h"
#include "Exporter/TeExporter.h"
#include "Exporter/TeTextureExportOptions.h"

namespace te
{
    WidgetToolBar::WidgetToolBar()
        : Widget(WidgetType::ToolBar)
    { 
        _title = TOOLBAR_TITLE;
    }

    WidgetToolBar::~WidgetToolBar()
    { }

    void WidgetToolBar::Initialize()
    {
        _flags =
            ImGuiWindowFlags_NoCollapse |
            ImGuiWindowFlags_NoResize |
            ImGuiWindowFlags_NoMove |
            ImGuiWindowFlags_NoSavedSettings |
            ImGuiWindowFlags_NoScrollbar |
            ImGuiWindowFlags_NoTitleBar;

        _onVisibleCallback = [this]()
        {
            float width = static_cast<float>(ImGui::GetWindowContentRegionMax().x - ImGui::GetWindowContentRegionMin().x);

            auto& ctx = *ImGui::GetCurrentContext();
            ctx.NextWindowData.MenuBarOffsetMinVal = ImVec2(ctx.Style.DisplaySafeAreaPadding.x, Math::Max(ctx.Style.DisplaySafeAreaPadding.y - ctx.Style.FramePadding.y, 0.0f));
            _position = Vector2(ctx.Viewports[0]->Pos.x, ctx.Viewports[0]->Pos.y + 25.0f);
            _size = Vector2(width, ctx.NextWindowData.MenuBarOffsetMinVal.y + ctx.FontBaseSize + ctx.Style.FramePadding.y + 18.0f);

            ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0, 5));
        };

        _onBeginCallback = [this]()
        {
            ImGui::PopStyleVar();
        };
    }

    void WidgetToolBar::Update()
    {
        // Play
        ImGuiExt::RenderButton(ICON_FA_PLAY, ICON_FA_STOP,
            []() { return !gCoreApplication().GetState().IsFlagSet(ApplicationState::Mode::Game); },
            []() { return true; },
            []() {
                gCoreApplication().GetState().ToggleFlag(ApplicationState::Mode::Game);
                gCoreApplication().GetState().ToggleFlag(ApplicationState::Mode::Physics);
                gCoreApplication().GetState().ToggleFlag(ApplicationState::Mode::Animation);
                gCoreApplication().GetState().ToggleFlag(ApplicationState::Mode::Scripting);
             
                bool isRunning = gCoreApplication().GetState().IsFlagSet(ApplicationState::Mode::Game);
                if (isRunning)
                {
                    gEditor().CreateRunningScene();
                }
                else
                {
                    gEditor().DestroyRunningScene();
                }
            }
        );

        // Guizmo translation
        ImGuiExt::RenderButton(ICON_FA_ARROWS_ALT, ICON_FA_ARROWS_ALT,
            []() { return !(gEditor().GetImGuizmoOperation() == ImGuizmo::OPERATION::TRANSLATE); },
            []() { return true; },
            []() { gEditor().SetImGuizmoOperation(ImGuizmo::OPERATION::TRANSLATE); }
        );

        // Guizmo rotation
        ImGuiExt::RenderButton(ICON_FA_SYNC, ICON_FA_SYNC,
            []() { return !(gEditor().GetImGuizmoOperation() == ImGuizmo::OPERATION::ROTATE); },
            []() { return true; },
            []() { gEditor().SetImGuizmoOperation(ImGuizmo::OPERATION::ROTATE); }
        );

        // Guizmo scale
        ImGuiExt::RenderButton(ICON_FA_COMPRESS_ALT, ICON_FA_COMPRESS_ALT,
            []() { return !(gEditor().GetImGuizmoOperation() == ImGuizmo::OPERATION::SCALE); },
            []() { return true; },
            []() { gEditor().SetImGuizmoOperation(ImGuizmo::OPERATION::SCALE); }
        );

        // Guizmo mode
        static ImGuiExt::ComboOptions<ImGuizmo::MODE> guizmoModeOptions;
        if (guizmoModeOptions.Options.size() == 0)
        {
            guizmoModeOptions.AddOption(ImGuizmo::MODE::LOCAL, "Local Space");
            guizmoModeOptions.AddOption(ImGuizmo::MODE::WORLD, "World Space");
        }

        ImGuizmo::MODE guizmoMode = gEditor().GetImGuizmoMode();

        ImGui::SameLine();
        if (ImGuiExt::RenderOptionCombo<ImGuizmo::MODE>((ImGuizmo::MODE*)(&guizmoMode), "##guizmo_mode_option", "", guizmoModeOptions, 150))
            gEditor().SetImGuizmoMode(guizmoMode);

#if TE_DEBUG_MODE == TE_DEBUG_ENABLED
        // RenderDoc
        ImGuiExt::RenderButton(ICON_FA_BUG, ICON_FA_BUG,
            []() { return true; },
            []() { return true; },
            []() { 
                gEditor().NeedsRedraw();
                RenderDocManager::Instance().FrameCapture();
            },
            ImVec2(),
            "Capture the next frame and then launch RenderDoc"
        );
#endif

        // Save all textures generated by the renderer to the disk
        ImGuiExt::RenderButton(ICON_FA_CAMERA_RETRO, ICON_FA_CAMERA_RETRO,
            []() { return true; },
            []() { return true; },
            []() {
                struct TextureElement
                {
                    SPtr<Texture> texture;
                    SPtr<TextureExportOptions> option;
                };

                gEditor().NeedsRedraw();
                Vector<TextureElement> textures;

                for (int i = 0; i != static_cast<int>(RenderOutputType::Count); i++)
                {
                    RenderOutputType renderType = static_cast<RenderOutputType>(i);
                    SPtr<Texture> texture = gRenderer()->GetLastRenderTexture(renderType);

                    if (texture)
                    {
                        TextureElement textureElement;

                        textureElement.texture = texture;
                        textureElement.option = TextureExportOptions::Create();

                        if (renderType == RenderOutputType::Depth)
                        {
                            textureElement.option->IsDepthStencilBuffer = true;
                            textureElement.option->IsSingleChannel = true;
                        }

                        if (renderType == RenderOutputType::SSAO)
                        {
                            textureElement.option->IsSingleChannel = true;
                        }

                        textures.push_back(textureElement);
                    }
                }

                Vector<HComponent> lights = gEditor().GetSceneRoot()->GetComponents(TID_CLight, true);
                for(const auto& light : lights)
                {
                    SPtr<Texture> texture = gRenderer()->GetLastShadowMapTexture(static_object_cast<CLight>(light).GetInternalPtr()->GetInternal());

                    if (texture)
                    {
                        TextureElement textureElement;

                        textureElement.texture = texture;
                        textureElement.option = TextureExportOptions::Create();

                        textures.push_back(textureElement);
                    }
                }

                UINT32 count = 0;
                for (const auto& texture : textures)
                {
                    gExporter().Export(texture.texture.get(), ToString(count) + ".jpeg", texture.option);
                    count++;
                }
            },
            ImVec2(),
            "Save all textures generated by the renderer to the disk"
        );
    }

    void WidgetToolBar::UpdateBackground()
    {
    }
}
