set (TE_MOTIONBLUR_INC_NOFILTER
    "TeApplication.h"
)

set (TE_MOTIONBLUR_SRC_NOFILTER
    "Main.cpp"
    "TeApplication.cpp"
)

source_group ("" FILES ${TE_MOTIONBLUR_SRC_NOFILTER} ${TE_MOTIONBLUR_INC_NOFILTER})

set (TE_MOTIONBLUR_SRC
    ${TE_MOTIONBLUR_INC_NOFILTER}
    ${TE_MOTIONBLUR_SRC_NOFILTER}
)
