language: cpp
os: linux

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - mesa-common-dev
            - libx11-dev
            - libxcursor-dev
            - libxrandr-dev
            - libxi-dev
            - uuid-dev
            - gcc-8
            - g++-8
            - libglfw3
            - libglfw3-dev
      env: 
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

before_install:
  - eval "${MATRIX_EVAL}"
  
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/Dependencies"

  # Download libUUID
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew install ossp-uuid
    fi

  # Download CMake
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.12/cmake-3.12.4-Linux-x86_64.tar.gz"
      cd ${DEPS_DIR}
      mkdir cmake
      travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake || brew upgrade cmake
    fi

  - cd ${TRAVIS_BUILD_DIR}

script:
  - INSTALL_DIR="${TRAVIS_BUILD_DIR}/Install"
  - mkdir ${INSTALL_DIR}
  - mkdir Build && cd Build
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      CC=gcc-8 CXX=g++-8 cmake -D CMAKE_C_COMPILER=gcc-8 -D CMAKE_CXX_COMPILER=g++-8 -DCMAKE_INSTALL_PREFIX:STRING=${INSTALL_DIR} .. 
    else
      cmake -DCMAKE_INSTALL_PREFIX:STRING=${INSTALL_DIR} ..
    fi
  - make
  - make install
  
after_success:
  - cd ..
  - today=`date +%Y.%m.%d`
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      buildName=${TRAVIS_TAG}
    else
      buildName=${today}
    fi
  - filename=tef_${buildName}_${TRAVIS_OS_NAME}.tar.gz
  - symbolsFilename=tef_${buildName}_${TRAVIS_OS_NAME}_symbols.tar.gz
  - cd ${INSTALL_DIR}
  - cd ..
  - |
    if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]] || [[ -n "$TRAVIS_TAG" ]]; then
      find ./Install -not -name "*.dbg" -not -name ".dwarf" -not -type d | cut -sd / -f 3- | tar -C ./Install -czvf ${filename} -T -
      find ./Install -name "*.dbg" -or -name "*.dwarf" -not -type d | cut -sd / -f 3- | tar -C ./Install -czvf ${symbolsFilename} -T -

      mkdir artifacts
      mv ${filename} artifacts
      mv ${symbolsFilename} artifacts
    fi