set (TE_GLIMGUIAPI_INC_NOFILTER
    "TeGLImGuiAPIPrerequisites.h"
    "TeGLImGuiAPIFactory.h"
    "TeGLImGuiAPI.h"
)

set (TE_GLIMGUIAPI_SRC_NOFILTER
    "TeGLImGuiAPIFactory.cpp"
    "TeGLImGuiAPI.cpp"
    "TeGLImGuiAPIPlugin.cpp"
)

set(TE_GLIMGUIAPI_INC_WIN32
)

set(TE_GLIMGUIAPI_SRC_WIN32
)

set(TE_GLIMGUIAPI_INC_LINUX
)

set(TE_GLIMGUIAPI_SRC_LINUX
)

source_group ("" FILES ${TE_GLIMGUIAPI_SRC_NOFILTER} ${TE_GLIMGUIAPI_INC_NOFILTER})
source_group("Win32" FILES ${TE_GLIMGUIAPI_INC_WIN32} ${TE_GLIMGUIAPI_SRC_WIN32})
source_group("Linux" FILES ${TE_GLIMGUIAPI_INC_LINUX} ${TE_GLIMGUIAPI_SRC_LINUX})

set (TE_GLIMGUIAPI_SRC
    ${TE_GLIMGUIAPI_INC_NOFILTER}
    ${TE_GLIMGUIAPI_SRC_NOFILTER}
)

if(WIN32)
    list(APPEND TE_GLIMGUIAPI_SRC
        ${TE_GLIMGUIAPI_INC_WIN32}
        ${TE_GLIMGUIAPI_SRC_WIN32}
    )
elseif(LINUX)
    list(APPEND TE_GLIMGUIAPI_SRC
        ${TE_GLIMGUIAPI_INC_LINUX}
        ${TE_GLIMGUIAPI_SRC_LINUX}
    )
endif()