set (TE_HELLOWORLD_INC_NOFILTER
    "TeApplication.h"
)

set (TE_HELLOWORLD_SRC_NOFILTER
    "Main.cpp"
    "TeApplication.cpp"
)

source_group ("" FILES ${TE_HELLOWORLD_SRC_NOFILTER} ${TE_HELLOWORLD_INC_NOFILTER})

set (TE_HELLOWORLD_SRC
    ${TE_HELLOWORLD_INC_NOFILTER}
    ${TE_HELLOWORLD_SRC_NOFILTER}
)
