set (TE_D3D11IMGUIAPI_INC_NOFILTER
    "TeD3D11ImGuiAPIPrerequisites.h"
    "TeD3D11ImGuiAPIFactory.h"
    "TeD3D11ImGuiAPI.h"
)

set (TE_D3D11IMGUIAPI_SRC_NOFILTER
    "TeD3D11ImGuiAPIFactory.cpp"
    "TeD3D11ImGuiAPI.cpp"
    "TeD3D11ImGuiAPIPlugin.cpp"
)

source_group ("" FILES ${TE_D3D11IMGUIAPI_SRC_NOFILTER} ${TE_D3D11IMGUIAPI_INC_NOFILTER})

set (TE_D3D11IMGUIAPI_SRC
    ${TE_D3D11IMGUIAPI_INC_NOFILTER}
    ${TE_D3D11IMGUIAPI_SRC_NOFILTER}
)
