set (TE_TESTS_INC_NOFILTER
)

set (TE_TESTS_SRC_NOFILTER
    "Main.cpp"
)

source_group ("" FILES ${TE_TESTS_SRC_NOFILTER} ${TE_TESTS_INC_NOFILTER})

set (TE_TESTS_SRC
    ${TE_TTESTS_INC_NOFILTER}
    ${TE_TESTS_SRC_NOFILTER}
)
