set (TE_LIGHTINGSCENE_INC_NOFILTER
    "TeApplication.h"
)

set (TE_LIGHTINGSCENE_SRC_NOFILTER
    "Main.cpp"
    "TeApplication.cpp"
)

source_group ("" FILES ${TE_LIGHTINGSCENE_SRC_NOFILTER} ${TE_LIGHTINGSCENE_INC_NOFILTER})

set (TE_LIGHTINGSCENE_SRC
    ${TE_LIGHTINGSCENE_INC_NOFILTER}
    ${TE_LIGHTINGSCENE_SRC_NOFILTER}
)
